use-msql-database: false #Turn on to use a MySQL database for storage of data for this plugin (recommended)
host: 'localhost'
port: '' #leave empty to use the default (1433)
user: 'root'
password: ''
database-name: 'vote_plugin_database'

load-finished-polls-before: 7 #You can specify after what time the finished polls are not going to be loaded (the time is provided in days) (type -1 to always load every finished poll saved in the database)
synchronize-database: 60 #You set how often (in minutes) the polls and voting data is going to be updated to the database (If set to 0 then it's going to be saved only on server close but please don't do that especially if you are not using mysql database)
announce-synchronize: false #If turned to true it's going to announce every time it synchronized to the database in the console