use-msql-database: false #Turn on to use a MySQL database for storage of data for this plugin (recommended)
host: 'localhost'
port: '' #leave empty to use the default (1433)
user: 'root'
password: ''

database-name: 'vote_plugin_database'