name: VotePlugin
version: '${project.version}'
main: me.trololo11.voteplugin.VotePlugin
api-version: '1.20'
commands:
  testcommand:
    description: "Only a text command dont worry :>"
  vote:
    description: "Vote on a poll"
  createpoll:
    description: "Creates a poll"
  seepolls:
    description: "See all polls"
  seepoll:
    description: "See a specific poll"
    usage: "/seepoll <poll code>"
permissions:
  voteplugin.createpolls:
    description: "Players with this permission can create polls"
  voteplugin.deletepolls:
    description: "Players with this permission can delete other player's polls"